import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./styles/**/*.css",
  ],
  theme: {
    extend: {
      colors: {
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: "hsl(var(--card))",
        "card-foreground": "hsl(var(--card-foreground))",
        popover: "hsl(var(--popover))",
        "popover-foreground": "hsl(var(--popover-foreground))",
        primary: "hsl(var(--primary))",
        "primary-foreground": "hsl(var(--primary-foreground))",
        secondary: "hsl(var(--secondary))",
        "secondary-foreground": "hsl(var(--secondary-foreground))",
        muted: "hsl(var(--muted))",
        "muted-foreground": "hsl(var(--muted-foreground))",
        accent: "hsl(var(--accent))",
        "accent-foreground": "hsl(var(--accent-foreground))",
        destructive: "hsl(var(--destructive))",
        "destructive-foreground": "hsl(var(--destructive-foreground))",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        info: "hsl(var(--info))",
        "info-soft": "hsl(var(--info-soft))",
        "info-foreground": "hsl(var(--info-foreground))",
        success: "hsl(var(--success))",
        "success-soft": "hsl(var(--success-soft))",
        "success-foreground": "hsl(var(--success-foreground))",
        caution: "hsl(var(--caution))",
        "caution-soft": "hsl(var(--caution-soft))",
        "caution-foreground": "hsl(var(--caution-foreground))",
        danger: "hsl(var(--danger))",
        "danger-soft": "hsl(var(--danger-soft))",
        "danger-foreground": "hsl(var(--danger-foreground))",
        /** Auction / bid / live urgency — not general brand */
        signal: "hsl(var(--performance-red))",
        "performance-red": "hsl(var(--performance-red))",
        "reserve-emerald": "hsl(var(--reserve-emerald))",
        "neon-blue": "hsl(var(--neon-blue))",
        "neon-lime": "hsl(var(--neon-lime))",
        /* Carasta Cyber-Luxury theme */
        "carasta-bg": "var(--carasta-bg)",
        "carasta-ink": "var(--carasta-ink)",
        "carasta-muted": "var(--carasta-muted)",
        "carasta-border": "var(--carasta-border)",
        "carasta-card": "var(--carasta-card-bg)",
        "carasta-blue": "var(--carasta-blue)",
        "carasta-red": "var(--carasta-red)",
        "carasta-white": "var(--carasta-white)",
      },
      fontFamily: {
        sans: ["var(--font-sans)", "system-ui", "sans-serif"],
        display: ["var(--font-display)", "var(--font-sans)", "system-ui", "sans-serif"],
        serif: ["var(--font-playfair)", "Playfair Display", "Georgia", "serif"],
      },
      borderRadius: {
        "2xl": "1rem",
      },
      boxShadow: {
        e1: "var(--shadow-e1)",
        e2: "var(--shadow-e2)",
        e3: "var(--shadow-e3)",
        glass: "0 8px 32px 0 rgba(0, 0, 0, 0.37)",
        "glass-sm": "0 4px 16px 0 rgba(0, 0, 0, 0.3)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
export default config;
