import path from "path";

import type { AssistantSourceDoc } from "@/lib/assistant/assistant-types";

const docsRoot = path.join(process.cwd(), "docs", "assistant");

export const assistantSourceRegistry: AssistantSourceDoc[] = [
  {
    id: "platform-overview",
    title: "Platform Overview",
    filePath: path.join(docsRoot, "platform-overview.md"),
    href: "/resources/what-is-carasta",
    summary: "What Carasta is, what it is for, and how Carmunity, marketplace, and seller tools fit together.",
    category: "platform",
    tags: ["carasta", "platform", "what is carasta", "overview", "product"],
    aliases: ["site", "website", "product", "app"],
  },
  {
    id: "community-and-conversation",
    title: "Community And Conversation",
    filePath: path.join(docsRoot, "community-and-conversation.md"),
    href: "/resources/what-is-carmunity",
    summary: "What Carmunity, Discussions, and Messages mean and how they fit into the platform.",
    category: "community",
    tags: ["carmunity", "discussions", "messages", "conversation", "community"],
    aliases: ["forum", "forums", "dm", "dms", "direct message", "chat"],
  },
  {
    id: "using-discussions-and-messages",
    title: "Using Discussions And Messages",
    filePath: path.join(docsRoot, "using-discussions-and-messages.md"),
    href: "/resources/discussions-basics",
    summary: "How to use Discussions, when to move to Messages, and how forum-style questions map to Carasta vocabulary.",
    category: "community",
    tags: ["discussions", "messages", "forums", "threads", "participation", "public conversation"],
    aliases: ["how do forums work", "how do discussions work", "how do i use messages"],
  },
  {
    id: "identity-and-garage",
    title: "Identity And Garage",
    filePath: path.join(docsRoot, "identity-and-garage.md"),
    href: "/resources/profiles-and-garage",
    summary: "How profiles and Garage fit into identity, trust, and participation.",
    category: "identity",
    tags: ["profile", "profiles", "garage", "identity", "dream garage"],
    aliases: ["account profile", "my profile", "cars"],
  },
  {
    id: "auctions-buying-and-selling",
    title: "Auctions Buying And Selling",
    filePath: path.join(docsRoot, "auctions-buying-and-selling.md"),
    href: "/resources/auction-basics",
    summary: "Auction basics plus general buyer and seller workflow framing.",
    category: "auctions",
    tags: ["auction", "auctions", "buying", "selling", "bid", "reserve"],
    aliases: ["bidding", "buyer", "seller", "sell", "buy"],
  },
  {
    id: "trust-safety-and-help",
    title: "Trust Safety And Help",
    filePath: path.join(docsRoot, "trust-safety-and-help.md"),
    href: "/resources/trust-and-safety",
    summary: "Trust boundaries, public help paths, and what the platform is and is not claiming.",
    category: "trust",
    tags: ["trust", "safety", "help", "support", "privacy", "terms", "guidelines"],
    aliases: ["legal", "policy", "contact", "moderation", "safe"],
  },
  {
    id: "seller-workspace-and-ai",
    title: "Seller Workspace And AI",
    filePath: path.join(docsRoot, "seller-workspace-and-ai.md"),
    href: "/u/[handle]/marketing",
    summary: "What the seller growth workspace and seller AI systems are for at a general level.",
    category: "seller",
    tags: ["seller", "workspace", "marketing", "listing ai", "copilot", "seller tools"],
    aliases: ["dashboard", "campaign", "ai", "marketing workspace"],
  },
  {
    id: "faq-and-glossary",
    title: "FAQ And Glossary",
    filePath: path.join(docsRoot, "faq-and-glossary.md"),
    href: "/resources/faq",
    summary: "High-signal FAQ answers and glossary terms for the core product vocabulary.",
    category: "faq",
    tags: ["faq", "glossary", "definitions", "terms", "vocabulary"],
    aliases: ["what does", "mean", "define"],
  },
  {
    id: "help-routing",
    title: "Help Routing",
    filePath: path.join(docsRoot, "help-routing.md"),
    href: "/contact",
    summary: "How to route users to Resources, Trust and Safety, or Contact based on the type of help they need.",
    category: "trust",
    tags: ["help", "contact", "support", "escalation", "where do i go"],
    aliases: ["where do i go", "who should i contact", "support route"],
  },
  {
    id: "navigation-and-help-paths",
    title: "Navigation And Help Paths",
    filePath: path.join(docsRoot, "navigation-and-help-paths.md"),
    href: "/resources",
    summary: "Where to start for product understanding, trust questions, direct help, and seller tool navigation.",
    category: "trust",
    tags: ["navigation", "help", "support", "where do i find", "where should i go"],
    aliases: ["where do i find", "where can i find", "how do i get to", "navigation"],
  },
];
