/**
 * Source: CARMUNITY_DISCUSSIONS_TAXONOMY.md — 20 Gears, 5–8 Lower Gears each.
 * Used by prisma/seed-taxonomy-gears.ts (idempotent upserts). Legacy Gears
 * (mechanics-corner, gear-interests) remain separate rows from ensureForumSpaces.
 */
export type TaxonomyLowerGear = { slug: string; title: string; sortOrder: number };

export type TaxonomyGear = {
  slug: string;
  title: string;
  description: string;
  sortOrder: number;
  lowers: TaxonomyLowerGear[];
};

export const TAXONOMY_GEARS: TaxonomyGear[] = [
  {
    slug: "track-hpde",
    title: "Track & HPDE",
    description: "Track days, HPDE, safety, telemetry, and competition licensing.",
    sortOrder: 100,
    lowers: [
      { slug: "hpde-101", title: "HPDE & track days 101", sortOrder: 1 },
      { slug: "coaching-line", title: "Coaching, instructors & line", sortOrder: 2 },
      { slug: "safety-equipment", title: "Helmets, HANS & safety gear", sortOrder: 3 },
      { slug: "telemetry-data", title: "Telemetry & data", sortOrder: 4 },
      { slug: "tracks-north-america", title: "Tracks & events (NA)", sortOrder: 5 },
      { slug: "tracks-international", title: "Tracks & events (international)", sortOrder: 6 },
      { slug: "competition-licensing", title: "Competition licensing & clubs", sortOrder: 7 },
      { slug: "open-lapping", title: "Open lapping & test days", sortOrder: 8 },
    ],
  },
  {
    slug: "road-canyon",
    title: "Road & Canyon",
    description: "Scenic drives, etiquette, and legal spirited driving culture.",
    sortOrder: 110,
    lowers: [
      { slug: "scenic-drives", title: "Scenic drives & routes", sortOrder: 1 },
      { slug: "spirited-not-street-racing", title: "Spirited driving (legal, safe)", sortOrder: 2 },
      { slug: "photography-spots", title: "Photo spots & meets etiquette", sortOrder: 3 },
      { slug: "tourism-road-trips", title: "Tourism & road trips", sortOrder: 4 },
      { slug: "weather-conditions", title: "Weather & road conditions", sortOrder: 5 },
      { slug: "local-regulations", title: "Local regulations & noise", sortOrder: 6 },
      { slug: "group-drives", title: "Group drives & pace cars", sortOrder: 7 },
    ],
  },
  {
    slug: "engine-drivetrain",
    title: "Engine & Drivetrain",
    description: "Engines, forced induction, fueling, cooling, transmissions.",
    sortOrder: 120,
    lowers: [
      { slug: "engine-builds", title: "Engine builds & swaps", sortOrder: 1 },
      { slug: "forced-induction", title: "Forced induction", sortOrder: 2 },
      { slug: "fueling-tuning", title: "Fueling & tuning", sortOrder: 3 },
      { slug: "exhaust-emissions", title: "Exhaust & emissions", sortOrder: 4 },
      { slug: "cooling-oiling", title: "Cooling & oiling", sortOrder: 5 },
      { slug: "transmissions-diffs", title: "Transmissions & differentials", sortOrder: 6 },
      { slug: "diagnostics-dtc", title: "Diagnostics & DTCs", sortOrder: 7 },
      { slug: "reliability-daily", title: "Reliability for daily use", sortOrder: 8 },
    ],
  },
  {
    slug: "suspension-chassis",
    title: "Suspension & Chassis",
    description: "Coilovers, alignment, bushings, corner weighting, aero balance.",
    sortOrder: 130,
    lowers: [
      { slug: "coilovers-shocks", title: "Coilovers & shocks", sortOrder: 1 },
      { slug: "springs-alignment", title: "Springs & alignment", sortOrder: 2 },
      { slug: "bushings-chassis", title: "Bushings & chassis hardware", sortOrder: 3 },
      { slug: "corner-weighting", title: "Corner weighting", sortOrder: 4 },
      { slug: "aero-balance", title: "Aero balance with mechanical grip", sortOrder: 5 },
      { slug: "street-vs-track-setup", title: "Street vs track setups", sortOrder: 6 },
    ],
  },
  {
    slug: "brakes-safety",
    title: "Brakes & Safety",
    description: "Pads, rotors, fluid, ABS, track temps, fire safety.",
    sortOrder: 140,
    lowers: [
      { slug: "pad-rotor-selection", title: "Pad & rotor selection", sortOrder: 1 },
      { slug: "fluid-brake-lines", title: "Fluid & lines", sortOrder: 2 },
      { slug: "abs-esc", title: "ABS & stability control", sortOrder: 3 },
      { slug: "track-brake-temps", title: "Track brake temps & bedding", sortOrder: 4 },
      { slug: "fire-safety", title: "Fire safety & extraction", sortOrder: 5 },
      { slug: "street-safety-gear", title: "Street safety gear", sortOrder: 6 },
    ],
  },
  {
    slug: "electrical-lighting",
    title: "Electrical & Lighting",
    description: "Wiring, lighting, audio integration, batteries, EV HV notes.",
    sortOrder: 150,
    lowers: [
      { slug: "wiring-harnesses", title: "Wiring & harnesses", sortOrder: 1 },
      { slug: "lighting-led", title: "Lighting & LED retrofits", sortOrder: 2 },
      { slug: "audio-head-units", title: "Audio integration (head units)", sortOrder: 3 },
      { slug: "batteries-charging", title: "Batteries & charging", sortOrder: 4 },
      { slug: "sensors-ecu", title: "Sensors & ECU interfaces", sortOrder: 5 },
      { slug: "ev-high-voltage-notes", title: "EV high-voltage notes (informational)", sortOrder: 6 },
    ],
  },
  {
    slug: "interior-audio",
    title: "Interior & Audio",
    description: "Seats, steering, cabin materials, sound deadening, SQ/SPL.",
    sortOrder: 160,
    lowers: [
      { slug: "seats-harnesses", title: "Seats & harnesses", sortOrder: 1 },
      { slug: "steering-wheels", title: "Steering wheels & controls", sortOrder: 2 },
      { slug: "cabin-materials", title: "Cabin materials & trim", sortOrder: 3 },
      { slug: "sound-deadening", title: "Sound deadening", sortOrder: 4 },
      { slug: "carplay-android", title: "CarPlay & Android Auto", sortOrder: 5 },
      { slug: "sq-spl-builds", title: "SQ & SPL builds", sortOrder: 6 },
    ],
  },
  {
    slug: "exterior-aero",
    title: "Exterior & Aero",
    description: "Body, splitters, wraps, weight reduction, fitment.",
    sortOrder: 170,
    lowers: [
      { slug: "body-panels", title: "Body panels & paint prep", sortOrder: 1 },
      { slug: "splitters-wings", title: "Splitters & wings", sortOrder: 2 },
      { slug: "canards-diffusers", title: "Canards & diffusers", sortOrder: 3 },
      { slug: "wraps-ppf", title: "Wraps & PPF", sortOrder: 4 },
      { slug: "weight-reduction", title: "Weight reduction (doors, glass)", sortOrder: 5 },
      { slug: "fitment-clearance", title: "Fitment & clearance", sortOrder: 6 },
    ],
  },
  {
    slug: "detailing-care",
    title: "Detailing & Care",
    description: "Wash methods, correction, interior leather, storage.",
    sortOrder: 180,
    lowers: [
      { slug: "wash-methods", title: "Wash methods & two-bucket", sortOrder: 1 },
      { slug: "correction-ceramic", title: "Correction & ceramic", sortOrder: 2 },
      { slug: "interior-leather", title: "Interior leather & alcantara", sortOrder: 3 },
      { slug: "engine-bays", title: "Engine bays & show prep", sortOrder: 4 },
      { slug: "storage-covering", title: "Storage & covering", sortOrder: 5 },
      { slug: "products-tools", title: "Products & tools", sortOrder: 6 },
    ],
  },
  {
    slug: "tools-shop",
    title: "Tools & Shop",
    description: "Garage setup, lifts, torque specs, specialty tools, safety.",
    sortOrder: 190,
    lowers: [
      { slug: "home-garage-setup", title: "Home garage setup", sortOrder: 1 },
      { slug: "lifts-jacks", title: "Lifts & jacks", sortOrder: 2 },
      { slug: "torque-specs", title: "Torque specs & procedures", sortOrder: 3 },
      { slug: "specialty-tools", title: "Specialty tools", sortOrder: 4 },
      { slug: "compressed-air", title: "Compressed air & pneumatics", sortOrder: 5 },
      { slug: "workspace-safety", title: "Workspace safety", sortOrder: 6 },
    ],
  },
  {
    slug: "restoration-classics",
    title: "Restoration & Classics",
    description: "Rust repair, period correctness, sourcing, paint, documentation.",
    sortOrder: 200,
    lowers: [
      { slug: "rust-repair", title: "Rust repair & metalwork", sortOrder: 1 },
      { slug: "period-correct", title: "Period-correct restorations", sortOrder: 2 },
      { slug: "sourcing-parts", title: "Sourcing NOS & reproduction parts", sortOrder: 3 },
      { slug: "paint-body", title: "Paint & body", sortOrder: 4 },
      { slug: "interiors-trim", title: "Interiors & trim", sortOrder: 5 },
      { slug: "documentation-history", title: "Documentation & history", sortOrder: 6 },
      { slug: "values-inspection", title: "Values & pre-purchase inspection", sortOrder: 7 },
    ],
  },
  {
    slug: "imports-jdm",
    title: "Imports & JDM",
    description: "Imports, JDM icons, parts forwarding, meet culture.",
    sortOrder: 210,
    lowers: [
      { slug: "import-process", title: "Import process & compliance (informational)", sortOrder: 1 },
      { slug: "jdm-icons", title: "JDM icons & chassis codes", sortOrder: 2 },
      { slug: "euro-imports", title: "Euro imports", sortOrder: 3 },
      { slug: "parts-forwarding", title: "Parts forwarding & brokers", sortOrder: 4 },
      { slug: "language-manuals", title: "Manuals & language barriers", sortOrder: 5 },
      { slug: "meet-culture", title: "Meet culture & etiquette", sortOrder: 6 },
    ],
  },
  {
    slug: "muscle-v8",
    title: "Muscle & V8",
    description: "Pushrod builds, LS swaps, carbs vs EFI, drag strip setup.",
    sortOrder: 220,
    lowers: [
      { slug: "pushrod-builds", title: "Pushrod builds", sortOrder: 1 },
      { slug: "ls-swaps", title: "LS & modern V8 swaps", sortOrder: 2 },
      { slug: "carb-vs-efi", title: "Carb vs EFI", sortOrder: 3 },
      { slug: "cooling-big-blocks", title: "Cooling big blocks", sortOrder: 4 },
      { slug: "drag-strip-setup", title: "Drag strip setup", sortOrder: 5 },
      { slug: "muscle-restoration", title: "Muscle restoration", sortOrder: 6 },
    ],
  },
  {
    slug: "ev-hybrid",
    title: "EV & Hybrid",
    description: "Charging, range, performance EV, battery health, hybrids.",
    sortOrder: 230,
    lowers: [
      { slug: "charging-home-road", title: "Charging at home & on the road", sortOrder: 1 },
      { slug: "range-real-world", title: "Range & real-world use", sortOrder: 2 },
      { slug: "performance-ev", title: "Performance EV tuning (policy-bound)", sortOrder: 3 },
      { slug: "battery-health", title: "Battery health & warranty", sortOrder: 4 },
      { slug: "hybrid-systems", title: "Hybrid systems", sortOrder: 5 },
      { slug: "track-ev", title: "Track use & thermals", sortOrder: 6 },
    ],
  },
  {
    slug: "wheels-tires",
    title: "Wheels & Tires",
    description: "Fitment, compounds, track wear, winter, TPMS.",
    sortOrder: 240,
    lowers: [
      { slug: "fitment-offsets", title: "Fitment & offsets", sortOrder: 1 },
      { slug: "tire-classes", title: "Tire classes & compounds", sortOrder: 2 },
      { slug: "track-tire-wear", title: "Track tire wear & heat cycles", sortOrder: 3 },
      { slug: "winter-all-season", title: "Winter & all-season", sortOrder: 4 },
      { slug: "tpm-sensors", title: "TPMS & sensors", sortOrder: 5 },
      { slug: "forged-vs-cast", title: "Forged vs cast wheels", sortOrder: 6 },
    ],
  },
  {
    slug: "overlanding-4x4",
    title: "Overlanding & 4x4",
    description: "Recovery, lift, racks, navigation, trail etiquette.",
    sortOrder: 250,
    lowers: [
      { slug: "recovery-gear", title: "Recovery gear & techniques", sortOrder: 1 },
      { slug: "suspension-lift", title: "Suspension lift & articulation", sortOrder: 2 },
      { slug: "roof-racks-storage", title: "Roof racks & storage", sortOrder: 3 },
      { slug: "navigation-comms", title: "Navigation & comms", sortOrder: 4 },
      { slug: "camping-rigs", title: "Camping rigs", sortOrder: 5 },
      { slug: "trail-etiquette", title: "Trail etiquette & Tread Lightly", sortOrder: 6 },
    ],
  },
  {
    slug: "motorcycles-two-wheel",
    title: "Motorcycles & Two-Wheel",
    description: "Gear, track days, commuting, maintenance, crossover culture.",
    sortOrder: 260,
    lowers: [
      { slug: "gear-atgatt", title: "Gear & ATGATT", sortOrder: 1 },
      { slug: "trackdays-bikes", title: "Track days (bikes)", sortOrder: 2 },
      { slug: "commuting", title: "Commuting & lane filtering", sortOrder: 3 },
      { slug: "maintenance-chain", title: "Maintenance & chain care", sortOrder: 4 },
      { slug: "touring-luggage", title: "Touring & luggage", sortOrder: 5 },
      { slug: "culture-crossover", title: "Culture crossover with cars", sortOrder: 6 },
    ],
  },
  {
    slug: "watches-horology",
    title: "Watches & Horology",
    description: "Drivers' watches, motorsport collabs, servicing, collecting.",
    sortOrder: 270,
    lowers: [
      { slug: "drivers-watches", title: "Drivers' watches & timing", sortOrder: 1 },
      { slug: "motorsport-collabs", title: "Motorsport collabs & editions", sortOrder: 2 },
      { slug: "servicing-authenticity", title: "Servicing & authenticity", sortOrder: 3 },
      { slug: "straps-track-use", title: "Straps & track use", sortOrder: 4 },
      { slug: "collecting-marketplace", title: "Collecting & marketplace etiquette", sortOrder: 5 },
    ],
  },
  {
    slug: "apparel-kit",
    title: "Apparel & Kit",
    description: "Helmets, suits, gloves, team merch, sizing.",
    sortOrder: 280,
    lowers: [
      { slug: "helmets-suits", title: "Helmets & suits", sortOrder: 1 },
      { slug: "gloves-footwear", title: "Gloves & footwear", sortOrder: 2 },
      { slug: "team-merch", title: "Team merch & drops", sortOrder: 3 },
      { slug: "lifestyle-brand", title: "Lifestyle brand discussion", sortOrder: 4 },
      { slug: "sizing-care", title: "Sizing & care", sortOrder: 5 },
    ],
  },
  {
    slug: "community-meets",
    title: "Community & Meets",
    description: "Local meets, clubs, charity drives, moderation meta, feedback.",
    sortOrder: 290,
    lowers: [
      { slug: "local-meets", title: "Local meets & Cars & Coffee", sortOrder: 1 },
      { slug: "club-organizing", title: "Club organizing", sortOrder: 2 },
      { slug: "charity-drives", title: "Charity drives", sortOrder: 3 },
      { slug: "new-members", title: "New members & introductions", sortOrder: 4 },
      { slug: "moderation-appeals", title: "Moderation & appeals (meta)", sortOrder: 5 },
      { slug: "feedback-product", title: "Product feedback for Carmunity", sortOrder: 6 },
      { slug: "photographers-media", title: "Photographers & media", sortOrder: 7 },
    ],
  },
];
